name: api_client
description: Package providing resources to communicate to the backend API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  equatable: ^2.0.5
  very_good_analysis: ^3.1.0
