name: book_repository
description: Package providing a repository for fetching data for books
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  api_client:
    path: ../api_client
  equatable: ^2.0.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.6
  very_good_analysis: ^3.1.0
