name: book_repository

on:
  pull_request:
    paths:
      - "packages/book_repository/**"
      - ".github/workflows/book_repository.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: ./packages/book_repository

    runs-on: ubuntu-latest

    container:
      image: dart:2.18.1

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings lib

      - name: Run tests
        run: dart test --test-randomize-ordering-seed random
