name: test_app

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "lib/**"
      - "test/**"

jobs:
  build:
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v3
        with:
          flutter-version: 3.3.2
          channel: "stable"
          cache: true

      - name: Cache Flutter artifacts
        uses: actions/cache@v2
        env:
          cache-name: cache-flutter-dependencies
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: |
            ./build
            ./.dart_tool

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --test-randomize-ordering-seed random
